### ISSUE TITLE
Time Chunking Breaks Discursive Diversity

### ISSUE THREAD

**Issue by xehu** [Watts-Lab/team-process-map#169]
When we chunk via time, DD breaks with the following error:

```
Traceback (most recent call last):
  File "/Users/xehu/Desktop/Team Process Map/team-process-map/feature_engine/featurize.py", line 29, in <module>
    feature_builder.featurize(col="message")
  File "/Users/xehu/Desktop/Team Process Map/team-process-map/feature_engine/feature_builder.py", line 144, in featurize
    self.conv_level_features()
  File "/Users/xehu/Desktop/Team Process Map/team-process-map/feature_engine/feature_builder.py", line 231, in conv_level_features
    self.conv_data = conv_feature_builder.calculate_conversation_level_features()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xehu/Desktop/Team Process Map/team-process-map/feature_engine/utils/calculate_conversation_level_features.py", line 61, in calculate_conversation_level_features
    self.get_discursive_diversity_features()
  File "/Users/xehu/Desktop/Team Process Map/team-process-map/feature_engine/utils/calculate_conversation_level_features.py", line 225, in get_discursive_diversity_features
    right=get_DD_features(self.chat_data, self.vect_data),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xehu/Desktop/Team Process Map/team-process-map/feature_engine/features/get_all_DD_features.py", line 43, in get_DD_features
    modulation_metrics = get_within_person_disc_range(chats_chunked, num_chunks)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xehu/Desktop/Team Process Map/team-process-map/feature_engine/features/within_person_discursive_range.py", line 26, in get_within_person_disc_range
    mean_vec_speaker_chunks.columns = ["_c".join(col).strip() for col in mean_vec_speaker_chunks.columns.values]
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xehu/Desktop/Team Process Map/team-process-map/feature_engine/features/within_person_discursive_range.py", line 26, in <listcomp>
    mean_vec_speaker_chunks.columns = ["_c".join(col).strip() for col in mean_vec_speaker_chunks.columns.values]
                                       ^^^^^^^^^^^^^^
TypeError: sequence item 1: expected str instance, float found
```

**Comment by xehu** [comment]
Ah, found the type error -- we needed to cast the chunk num to a string. solved!
