### ISSUE TITLE
Bug in turn preprocessing

### ISSUE THREAD

**Issue by xehu** [Watts-Lab/team-process-map#194]
```
Traceback (most recent call last):
  File "/Users/xehu/Desktop/Team Process Mapping/team-process-map/feature_engine/featurize.py", line 56, in <module>
    reddit_feature_tester = FeatureBuilder(
                            ^^^^^^^^^^^^^^^
  File "/Users/xehu/Desktop/Team Process Mapping/team-process-map/feature_engine/feature_builder.py", line 88, in __init__
    self.preprocess_chat_data(col="message", turns=self.turns, conversation_id = self.conversation_id, cumulative_grouping = self.cumulative_grouping, within_task = self.within_task)
  File "/Users/xehu/Desktop/Team Process Mapping/team-process-map/feature_engine/feature_builder.py", line 232, in preprocess_chat_data
    self.chat_data = preprocess_naive_turns(self.chat_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xehu/Desktop/Team Process Mapping/team-process-map/feature_engine/utils/preprocess.py", line 47, in preprocess_naive_turns
    turn_id_per_conv = turn_id_per_conv.to_frame().reset_index().rename(columns={0:'turn_id'})
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xehu/anaconda3/envs/tpm_virtualenv/lib/python3.11/site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'to_frame'
```

**Comment by xehu** [comment]
I ran the current version of the featurizer on a bunch of test datasets and wasn't able to replicate the issue. Closing for now!
